project:
  type: book
  output-dir: docs

book:
  title: "Solucionaro de Control Automático de Procesos"
  author: "Ever Vino"
  page-navigation: true
  
  date: "9/1/2023"
  chapters:
    - index.qmd
    - part: Sistemas físicos de primer orden
      chapters:
        - p5.1-babatunde.qmd
        - p5.1-coughanowr.qmd
        - p5.2-coughanowr.qmd
        - p5.3-coughanowr.qmd
        - p5.5-coughanowr.qmd
        - p5.5-seborg.qmd
        - p5.9-coughanowr.qmd
        - p5.9-seborg.qmd
        - p5.16-coughanowr.qmd
        - p5.18-coughanowr.qmd
        - p5.21-seborg.qmd

    - part: Sistemas físicos de segundo orden 
      chapters:
        - p7.2-coughanowr.qmd
        - p7.3-coughanowr.qmd 

bibliography: references.bib
number-depth: 0
format:
  
  html:
  
    theme: 
    - cosmo
    - custom.scss
    
    html-math-method: katex
  pdf:
    documentclass: scrreprt



